In [2]:
import numpy as np

# Numpy

<hr>
<hr>

# ベクトル

<hr>

## ベクトル の宣言

In [5]:
# ベクトル の宣言はnumpy.array()を利用する
x = np.array([1,2,3])
print(x)

[1 2 3]


In [6]:
#型はndarray型
type(x)

numpy.ndarray

<hr>

### 要素が等間隔になるベクトル の宣言

#### 1. numpy.arangeを使う

In [7]:
#numpy.arange([start=0, ]stop, [step=1, ]dtype=None)を利用する
#始点start、終点stop、間隔stepの等差数列となるようなベクトルを生成する。
#ただし、終点stopの値はベクトルに含まれない。

x = np.arange(10,100,10)
print(x)

[10 20 30 40 50 60 70 80 90]


#### 2. numpy.linspaceを使う

In [4]:
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#stop:終点。この値も生成されるベクトルに含まれる
#num:始点~終点間に設定する点の数
#linspaceで生成されるベクトルは、要素間の間隔が全て等しくなるように設定される。
#numはデフォルトで50、retstep=Trueにすると間隔も返ってくる。

x = np.linspace(10,100,10)
print(x)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


<hr>

## ベクトルのノルム(大きさ)

### numpy.linalg.norm()を使う

In [6]:
#numpy.linalg.norm(ベクトル)でbベクトルのノルムが算出できる。

x = np.linspace(10,100,10)
print("x:{}".format(x))
print("norm:{}".format(np.linalg.norm(x)))

x:[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
norm:196.21416870348583


<hr>
<hr>

# 行列

<hr>

## 行列の宣言

### numpy.arrayで2次元リストを使う

In [7]:
#numpy.array()で２次元リストを引数にすると行列が作られる。

x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [9]:
#リストの長さがバラバラで行列が作れないなどの時は、各行を１要素とした行列になる

x = np.array([[1,2],[3,4,5],[6,7,8,9]])
print(x)

[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


In [12]:
#ちなみに行列の型はnumpy.ndarray型である
type(x)

numpy.ndarray

### 要素を書き換える

In [11]:
#行列の要素を書き換えたいときはリストの時と同様にインデックスを指定して書き換える。

x = np.array([[1,2,3],[4,5,6]])
print(x)

#x[1][1]を100にする
x[1][1]=100
print(x)

[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [  4 100   6]]


<hr>

## 行列の型(サイズ)

### numpy.ndarrayの属性shape

In [13]:
#numpy.ndarray型の属性"shape"でわかる

x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


<hr>

## 零行列

### numpy.zeros()

In [14]:
#numpy.zeros(n)でその長さ分の零ベクトル

x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#numpy.zeros((x,y))でx*yの零行列

x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<hr>

## 要素が全て1の行列

### numpy.ones()

In [16]:
#numpy.ones(n)でその長さ分の行列

x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#numpy.ones((x,y))でその次元の行列

x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<hr>

## 要素がランダムの行列

### numpy.random.rand()

In [18]:
#numpy.random.rand(n)でその長さ分のベクトル

x=np.random.rand(10)
x

array([0.85160542, 0.5962961 , 0.59507194, 0.42019775, 0.99072785,
       0.65013571, 0.11765969, 0.96218967, 0.43043287, 0.09963496])

In [19]:
#引数2つで行列が生成

x=np.random.rand(2,3)
x

array([[0.18313263, 0.33531179, 0.60365934],
       [0.24072959, 0.79571772, 0.80547101]])

### numpy.random.randint()

In [23]:
#生成する数の範囲を指定したい時はrandintを使う
#引数は始点,終点,(行列の次元)

x=np.random.randint(9,11,(3,3))
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

<hr>

## 行列のサイズを変更する

### numpy.reshape()

In [24]:
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

In [25]:
#numpy.reshape(m,n)でm*n型行列に変える
x.reshape(1,9)

array([[10, 10, 10, 10, 10,  9, 10, 10,  9]])

In [27]:
#行列の要素数とreshapeした後の行列の要素数が異なるとエラー
x.reshape(10,10)

ValueError: cannot reshape array of size 9 into shape (10,10)

## スカラー演算

In [30]:
#スカラーと行列をかけたい時は
#普通にスカラーとndarray型行列をかければ良い。

In [28]:
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

In [29]:
10*x

array([[100, 100, 100],
       [100, 100,  90],
       [100, 100,  90]])