In [2]:
import numpy as np

# Numpy

<hr>
<hr>

# ベクトル

<hr>

## ベクトル の宣言

In [5]:
# ベクトル の宣言はnumpy.array()を利用する
x = np.array([1,2,3])
print(x)

[1 2 3]


In [6]:
#型はndarray型
type(x)

numpy.ndarray

<hr>

### 要素が等間隔になるベクトル の宣言

#### 1. numpy.arangeを使う

In [7]:
#numpy.arange([start=0, ]stop, [step=1, ]dtype=None)を利用する
#始点start、終点stop、間隔stepの等差数列となるようなベクトルを生成する。
#ただし、終点stopの値はベクトルに含まれない。

x = np.arange(10,100,10)
print(x)

[10 20 30 40 50 60 70 80 90]


#### 2. numpy.linspaceを使う

In [4]:
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#stop:終点。この値も生成されるベクトルに含まれる
#num:始点~終点間に設定する点の数
#linspaceで生成されるベクトルは、要素間の間隔が全て等しくなるように設定される。
#numはデフォルトで50、retstep=Trueにすると間隔も返ってくる。

x = np.linspace(10,100,10)
print(x)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


<hr>

## ベクトルのノルム(大きさ)

### numpy.linalg.norm()を使う

In [6]:
#numpy.linalg.norm(ベクトル)でbベクトルのノルムが算出できる。

x = np.linspace(10,100,10)
print("x:{}".format(x))
print("norm:{}".format(np.linalg.norm(x)))

x:[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
norm:196.21416870348583


<hr>
<hr>

# 行列

<hr>

## 行列の宣言

### numpy.arrayで2次元リストを使う

In [7]:
#numpy.array()で２次元リストを引数にすると行列が作られる。

x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [9]:
#リストの長さがバラバラで行列が作れないなどの時は、各行を１要素とした行列になる

x = np.array([[1,2],[3,4,5],[6,7,8,9]])
print(x)

[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


In [12]:
#ちなみに行列の型はnumpy.ndarray型である
type(x)

numpy.ndarray

### 要素を書き換える

In [11]:
#行列の要素を書き換えたいときはリストの時と同様にインデックスを指定して書き換える。

x = np.array([[1,2,3],[4,5,6]])
print(x)

#x[1][1]を100にする
x[1][1]=100
print(x)

[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [  4 100   6]]
