In [2]:
import numpy as np

# Numpy

<hr>
<hr>

# ベクトル

<hr>

## ベクトル の宣言

In [5]:
# ベクトル の宣言はnumpy.array()を利用する
x = np.array([1,2,3])
print(x)

[1 2 3]


In [6]:
#型はndarray型
type(x)

numpy.ndarray

<hr>

### 要素が等間隔になるベクトル の宣言

#### 1. numpy.arangeを使う

In [7]:
#numpy.arange([start=0, ]stop, [step=1, ]dtype=None)を利用する
#始点start、終点stop、間隔stepの等差数列となるようなベクトルを生成する。
#ただし、終点stopの値はベクトルに含まれない。

x = np.arange(10,100,10)
print(x)

[10 20 30 40 50 60 70 80 90]


#### 2. numpy.linspaceを使う

In [4]:
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#stop:終点。この値も生成されるベクトルに含まれる
#num:始点~終点間に設定する点の数
#linspaceで生成されるベクトルは、要素間の間隔が全て等しくなるように設定される。
#numはデフォルトで50、retstep=Trueにすると間隔も返ってくる。

x = np.linspace(10,100,10)
print(x)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


<hr>

## ベクトルのノルム(大きさ)

### numpy.linalg.norm()を使う

In [6]:
#numpy.linalg.norm(ベクトル)でbベクトルのノルムが算出できる。

x = np.linspace(10,100,10)
print("x:{}".format(x))
print("norm:{}".format(np.linalg.norm(x)))

x:[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
norm:196.21416870348583


<hr>
<hr>

# 行列

<hr>

## 行列の宣言

### numpy.arrayで2次元リストを使う

In [7]:
#numpy.array()で２次元リストを引数にすると行列が作られる。

x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [9]:
#リストの長さがバラバラで行列が作れないなどの時は、各行を１要素とした行列になる

x = np.array([[1,2],[3,4,5],[6,7,8,9]])
print(x)

[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


In [12]:
#ちなみに行列の型はnumpy.ndarray型である
type(x)

numpy.ndarray

### 要素を書き換える

In [11]:
#行列の要素を書き換えたいときはリストの時と同様にインデックスを指定して書き換える。

x = np.array([[1,2,3],[4,5,6]])
print(x)

#x[1][1]を100にする
x[1][1]=100
print(x)

[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [  4 100   6]]


<hr>

## 行列の型(サイズ)

### numpy.ndarrayの属性shape

In [13]:
#numpy.ndarray型の属性"shape"でわかる

x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


<hr>

## 零行列

### numpy.zeros()

In [14]:
#numpy.zeros(n)でその長さ分の零ベクトル

x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#numpy.zeros((x,y))でx*yの零行列

x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<hr>

## 要素が全て1の行列

### numpy.ones()

In [16]:
#numpy.ones(n)でその長さ分の行列

x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#numpy.ones((x,y))でその次元の行列

x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<hr>

## 要素がランダムの行列

### numpy.random.rand()

In [18]:
#numpy.random.rand(n)でその長さ分のベクトル

x=np.random.rand(10)
x

array([0.85160542, 0.5962961 , 0.59507194, 0.42019775, 0.99072785,
       0.65013571, 0.11765969, 0.96218967, 0.43043287, 0.09963496])

In [19]:
#引数2つで行列が生成

x=np.random.rand(2,3)
x

array([[0.18313263, 0.33531179, 0.60365934],
       [0.24072959, 0.79571772, 0.80547101]])

### numpy.random.randint()

In [23]:
#生成する数の範囲を指定したい時はrandintを使う
#引数は始点,終点,(行列の次元)

x=np.random.randint(9,11,(3,3))
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

<hr>

## 行列のサイズを変更する

### numpy.reshape()

In [24]:
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

In [25]:
#numpy.reshape(m,n)でm*n型行列に変える
x.reshape(1,9)

array([[10, 10, 10, 10, 10,  9, 10, 10,  9]])

In [27]:
#行列の要素数とreshapeした後の行列の要素数が異なるとエラー
x.reshape(10,10)

ValueError: cannot reshape array of size 9 into shape (10,10)

## スカラー演算

In [30]:
#スカラーと行列をかけたい時は
#普通にスカラーとndarray型行列をかければ良い。

In [28]:
x

array([[10, 10, 10],
       [10, 10,  9],
       [10, 10,  9]])

In [29]:
10*x

array([[100, 100, 100],
       [100, 100,  90],
       [100, 100,  90]])

<hr>

## 行列積（ベクトルの内積）

### numpy.dot(行列1,行列2)

In [35]:
#行列a,b用意
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [36]:
#a*b

np.dot(a,b)

array([[22, 28],
       [49, 64]])

### (行列1).dot(行列2)

In [37]:
a.dot(b)

array([[22, 28],
       [49, 64]])

<hr>

## 転置行列

### (行列).T

In [38]:
#(ndarray型の変数).Tで転置行列を算出できる

print("行列a:")
print(a)

print("行列aの転置行列:")
print(a.T)

行列a:
[[1 2 3]
 [4 5 6]]
行列aの転置行列:
[[1 4]
 [2 5]
 [3 6]]


<hr>

## 単位行列

### numpy.identity(n)

In [40]:
#numpy.identity(n) で n*nの単位行列

print("5*5の単位行列:")
print(np.identity(5))

5*5の単位行列:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<hr>

## 逆行列

### numpy.linalg.inv(A)

In [44]:
#逆行列を算出したい時はnumpy.linalg.inv(行列A)

c=np.array([[1,4,2],[3,1,5],[2,1,3]])

print("行列C:")
print(c)

print("行列Cの逆行列:")
print(np.linalg.inv(c))

行列C:
[[1 4 2]
 [3 1 5]
 [2 1 3]]
行列Cの逆行列:
[[-0.5  -2.5   4.5 ]
 [ 0.25 -0.25  0.25]
 [ 0.25  1.75 -2.75]]


In [45]:
#逆行列を算出できない行列の時はエラー

print("行列A:")
print(a)

print("行列Aの逆行列:")
print(np.linalg.inv(a))

行列A:
[[1 2 3]
 [4 5 6]]
行列Aの逆行列:


LinAlgError: Last 2 dimensions of the array must be square

<hr>
<hr>

# ファイルに保存

<hr>

## ndarray型のデータをファイルに保存する

### numpy.save(‘ファイル名.npy’,変数名)

In [46]:
#ndarray型変数をファイルに保存するにはnumpyの関数save(‘ファイル名.npy’,変数名)を利用する。
#引数には保存するファイル名(拡張子は.npy)と保存する変数名を入力する。

np.save('a.npy',a)

### numpy.savez(‘ファイル名.npz’,変数名1=変数名1,変数名2=変数名2,,,)

In [47]:
#複数の変数を保存したい時はnumpyの関数savez(‘ファイル名.npz’,変数名1=変数名1,変数名2=変数名2,,,)を使用する。

np.savez('ab.npz',a=a,b=b)

<hr>

## ファイルからndarray型のデータを読み込む

### numpy.load('ファイル名')

In [49]:
#保存した.npyファイルを読み出すにはnumpyの関数load(‘ファイル名.npy’)を利用する。

data=np.load('a.npy')

print(data)

[[1 2 3]
 [4 5 6]]


In [51]:
#npzの時は、files属性で格納されているデータを確認する

datum=np.load('ab.npz')

print(datum.files)

['a', 'b']


In [52]:
#その後、インデックスを使って表示させる

print(datum['a'])
print(datum['b'])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
